spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: allin
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

server:
  servlet:
    encoding:
      force: true

logging:
    level:
      ai.assistant: debug
      org.springframework: info
      io.grpc: info
